"""后端 PUT /api/config/file 写入配置测试脚本（生成时间: 2025-11-15T20:49:34+08:00）"""

import backend.tests._path  # noqa: F401
from tests_shared.scenario import ApiScenario, StepConfig

GENERATED_AT = "2025-11-15T20:49:34+08:00"

scenario = ApiScenario(
    functionality="config_file_put",
    category="backend",
    description="PUT /api/config/file 覆盖写入 data",
    generated_at=GENERATED_AT,
    steps=[
        StepConfig(
            name="put_config",
            method="PUT",
            path="/api/config/file",
            description="写入自动化测试配置",
            json_body={
                "data": {
                    "tests": {
                        "configWrite": True,
                        "notes": "generated by automation"
                    }
                }
            },
        ),
    ],
)

if __name__ == "__main__":
    scenario.run()
